### ISSUE TITLE
Lstm cnn shape

### ISSUE THREAD

**Issue by soans1994** [Aminullah6264/BidirectionalLSTM#3]
Hello authors,

Your paper is great motivation for lstm research.
- I want to ask that you are using lstm models after extracting the cnn features. Can you tell the input size of the lstm model.
Ex: (bs, frame_number, features size)

- and this is different from conv2dlstm that is provided by the tensor flow ? Which applies lstm for each conv operation.

thank you

**Comment by aminullah6264** [comment]
I have updated the code to Pytorch, which is much easier to follow.
